lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'

    # access_token's time-to-live in seconds (eg., 3600: 1 hour)
    token_ttl: '%env(JWT_ACCESS_TOKEN_TTL)%'

    # Allowed clock skew in seconds for `nbf` and `exp` validation
    clock_skew: 0
