import {
  ApiException,
  ForbiddenException,
  NetworkException,
  ServerException,
  UnauthorizedException,
  ValidationException,
} from "@/lib/api/exceptions";
import { logger } from "@/lib/utils/Logger";

/**
 * A client-safe mapping dictionary that translates authentication error codes
 * into human-readable, localized (French) UI notifications.
 *
 * @remarks
 * **Security Notice:**
 * To mitigate information disclosure and user enumeration vulnerabilities,
 * user-facing messages must remain intentionally ambiguous (e.g., combining
 * invalid username and invalid password failures into a single generic phrase).
 * Never expose raw backend exceptions, stack traces, or internal infrastructure data here.
 *
 * Supports both native NextAuth error strings and custom codes mapped by the `AuthErrorFactory`.
 *
 * @type {Record<string, string>}
 *
 * @example
 * ```typescript
 * const message = AUTH_ERROR_MESSAGES["CredentialsSignin"];
 * // returns "Identifiant ou mot de passe incorrect."
 * ```
 */
const AUTH_ERROR_MESSAGES: Record<string, string> = {
  // NextAuth native codes
  CredentialsSignin: "Identifiant ou mot de passe incorrect.",
  AccessDenied: "Accès refusé.",
  Verification: "Le lien de connexion est invalide ou expiré.",

  // AuthErrorFactory codes (for custom handling/pages)
  INVALID_CREDENTIALS: "Identifiant ou mot de passe incorrect.",
  NETWORK_FAILURE: "Problème de connexion réseau. Veuillez réessayer.",
  REMOTE_SERVER_ERROR: "Le serveur d'authentification est indisponible.",
  UNKNOWN_AUTH_ERROR: "Une erreur d'authentification est survenue.",
};

/**
 * Translates NextAuth error codes or custom authentication error tokens
 * into localized, user-friendly error messages for UI presentation.
 *
 * @remarks
 * **Security Warning:** This function acts as an information disclosure barrier.
 * To prevent username enumeration attacks, generic errors like `CredentialsSignin`
 * are mapped to ambiguous messages ("Identifiant ou mot de passe incorrect.") so
 * attackers cannot deduce whether a username exists or if only the password was wrong.
 *
 * @param error - The raw error string code forwarded from NextAuth's `signIn` response
 *                or generated by the internal application layer (e.g., 'CredentialsSignin', 'AccessDenied').
 *
 * @returns A safe, localized (French) human-readable error string ready to be rendered
 *          in form alerts. Defaults to a generic fallback message if the error token is missing or unmapped.
 *
 * @example
 * ```typescript
 * // Usage in your React Hook Form onSubmit handler:
 * if (response?.error) {
 *   setError("root.serverError", {
 *     message: getAuthErrorMessage(response.error),
 *   });
 * }
 * ```
 */
export function getAuthErrorMessage(error?: string): string {
  if (!error) {
    return "Une erreur d'authentification est survenue.";
  }

  return (
    AUTH_ERROR_MESSAGES[error] ?? "Une erreur d'authentification est survenue."
  );
}

/**
 * Belongs to your Application/Authentication Layer. Its sole responsibility is
 * to take domain/system exceptions and translate them into application-level
 * security states or URL-friendly strings (ACCOUNT_DISABLED, INVALID_CREDENTIALS)
 * required specifically by NextAuth.
 */

/**
 * A specialized factory responsible for translating domain-specific API and network exceptions
 * into standardized, URL-friendly security error string codes required by NextAuth.
 *
 * @remarks
 * This class belongs to the **Application/Authentication Layer** and acts as a security boundary
 * between your internal backend infrastructure and the client-facing authentication responses.
 * By collapsing highly specific exceptions into generic error strings, it prevents information disclosure
 * and helps mitigate user enumeration attacks.
 *
 * @example
 * ```typescript
 * try {
 *   const user = await authService.login(username, password);
 *   return user;
 * } catch (error) {
 *   // Translates internal ApiException into a standard Error wrapped with a token code
 *   throw AuthErrorFactory.from(error);
 * }
 * ```
 */
export class AuthErrorFactory {
  /**
   * Translates internal API exceptions into distinct error strings
   * that NextAuth will pass to the login redirect URL (?error=CODE)
   */
  static from(error: unknown): Error {
    logger("error", "AuthErrorFactory.from", { error });

    // 1. Handle explicit API Exceptions
    if (error instanceof ApiException) {
      /**
       * 401
       */
      if (error instanceof UnauthorizedException) {
        return new Error("INVALID_CREDENTIALS");
      }

      /**
       * 403
       */
      if (error instanceof ForbiddenException) {
        return new Error("ACCESS_FORBIDDEN");
      }

      /**
       * 422
       */
      if (error instanceof ValidationException) {
        return new Error("INVALID_INPUT_FORMAT");
      }

      /**
       * 5xx
       */
      if (error instanceof ServerException) {
        return new Error("REMOTE_SERVER_ERROR");
      }
    }

    // 2. Handle Network or Timeout exceptions
    if (error instanceof NetworkException) {
      return new Error("NETWORK_FAILURE");
    }

    // 3. Fallback for unhandled anomalies
    return new Error("UNKNOWN_AUTH_ERROR");
  }
}
